### ISSUE TITLE
Is num_steps for pretraining must be at least 20000?

### ISSUE THREAD

**Issue by Giyaddy** [yaushian/Unparalleled-Text-summarization-using-GAN#4]
I have tested your python codes in google colaboratory. I knew that the dataset (in this case, Sent-Summary) is too large for training and testing the model in colab, so I just take about 20k first data from both train.article.txt and train.title.txt. But, when I run this command :

_python3 main.py -pretrain -model_dir model_results/ -num_steps 100_

The codes are never outputting the pretrain model in [model_path]/generator. (For your information, I just use 100 as my  num_steps value, because the time for training was too long). How to solve this issue? Am I have to use 20000 as my num_steps value or there is something else that can be a solution for this problem? Thanks

**Comment by joshyii** [comment]
I want to know more about this. I have trained for 20000 steps, but still there is nothing in [model_path]/generator

**Comment by lacie-life** [comment]
@joshyii Do you solve that? I have the same problem. Thank you!
